language: scala
matrix:
  include:
  - jdk: openjdk8
    scala: 2.13.2
    env: BINTRAY_PUBLISH=true
  - jdk: openjdk11
    scala: 2.13.2
    env: BINTRAY_PUBLISH=false
git:
  depth: 10
script:
- ./scripts/buildViaTravis.sh
sudo: required
dist: xenial
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
env:
  global:
  - secure: PZd2+8Vw4ykUQ5S5M704wo3isqFobYIuQCuLPxxVrz+vPGp6Vz7OrxMi2n71Evb9buv383gXkqO1I5Y2ceWaiOiAn31twobWINpYxwUFMoqbCfhYV9xFNVYQluUCxp4NtsgY19UQ1AyrUVVI1c1nF9zfbdJ+S63gP3DVQjwZH4+ptHMtylND8L9uhqbWhrKmKWnUkqHU+gH7S+PmQf2P+8iiyijg/EmFci3yNQtI7IQgR5MfRdG3a5hFRXydoVSGt+0fFrgDNqNVAxkkVxPgkMGKFAcbidAg7LCJWNyU9WngjAGAmBvea/Cs3D3yPiq0ie0jeR7GDXR3lHTqeiJmz/hNHDhMEQ9PKBTQcntzeE0ZwUXyvxZZHxb2vZnTJaRmq/zxeDM8jPbXR6Sm3UAqlQ0vp2TqINNgZJ2LTDjGu0zCtvCZe7GD1TLR20CFkFTtzBZi1Er15UcFuv5BknjE5w0u2ImsgizsUT2NKwB3rNYmo0VdJe+qIH71ao7lUE8hjUZeXpEBREdxOLB81jSjxGjxQV2/77XOFTsV8RWV9ftvccRnWSAPm1geRP9KGzkQ5Go7FHA+M6zuEdLZ5XhOg7fmPpVsuHHabT+KVfAjAoBZRg+so7Umy40t68aNNoU/1EDSBh8Mv3hNHV46CSTurxyWL+yU04VXK77vArSmXu4=
  - secure: ASj77aD6ZmBkJq4sJPQmYZTKBp/Foc/RGk6SUgrpDv8tWAyqvbkWp5qB3iy910HnLkzUNDPp3Fre1eeoQwh5htkVSxrzcEPSMPoyC5s03gp1sHd5QIxhD0MtCimVkb13z2WSHfotnFVJfQyz4VzMFVpRV0qj/al7OPwz+75a/SgDysiuPQ0XDO+nL/6dloui6kxNqxKIeZHinvz2J9hwpGNxRjTNlvqAjPLuFmM6kNVtNnfonfJHQ9WRiAyLAz27j2AIEUKEXbLKDbJIUrCN74/uxvDJ8/QmQdLXxSAtgc+fUKAG1RYwBslAsrfoilCsVNaVE9IeRIcbDmmB6TXqcYw0g+lSAwbkf3Oz64jVMo+E2XSLsz3AdFOJ+eewvPU8eZCepg3jszEVZtJWwUiScEFIXjaFmbZmaAK5pgEgChZo8Ps1pK0bbXt+85hC8VB+pUV0fBxnsEtLoP5jLorPC5gwFeHeQ+STy6K9OA8R3jb81Nm+uS3Bp5hezvJdOfS3umjLclvnK4mH/2Ot9NQkW/t+WL4dLQInqP5ZdOMGODI0O+6iRbuZqEbdrvaVEsJbek1So2BJeBB6VUgLGAv88Iq3rQgAVbQLOjH3n+tixl345aeIBnEQFeicrpJHXu7nm0FyEandW8Gjhh9/iiGN1v8nFSOOyy+4r6TIc9Ie+Lk=
  - secure: dlXWw5GoUzMt8aS8+ZJ5Hs4fd/wKZox1LZv3o2kxlML8rvOSEe5Z9FeR9xo+BlcMcKMcGrLHbTZEiYplf6GwaNpeCAtexcvhZ/wz6GHh1vRQD5NUjBmq9TuiOKdlS45nK+2iPUKbdNrF80oSjuz6evrLy50Ss6pAZqpIozAoYx5FfFOaIyZjLtw078uenpbJ3DIoHeEKKfemoRge+1bAHD3MB/A3qg8iTM0q2n2LgOS9mvQhYOAt5tmcRm3UY5GdR+IuhYssTn6XhHl7/+kGthylHk14NpAtMEtc6zBrPYxZ0iIPdhtM3FpSExy5yoUDTcmuS9oruwX7qTLznYNL+CHxhDR3pEA+7eWz2Pu4qz4g0a2BH8hgHC0Vn7141sboQsHVJ0IsoBlgVmgbI443++x+gVviPuC9OcInOilYGUGr9kdlXw58D/2Z7yz0ZSvxTZ7ichQg+74WMhlCgV8mww1x4LO2OaDsBP5pfHBcciztvRwDgckEY0Gh23oez0XeQX92qAebtLLqVZuGA74SGuso/bsTLOaucOcfiVSy84UFY9MyBkKHoqFLlxkpneovPh9rDbv3tDhlhhsg+PoVdNW/uyY+oP79IC17ZOQmLKcJ5F2s1tnuCRonWpofR0K955YeVO4GJPzKr6zW7hqANvWQelHqq1HmK1ebj6dM/+E=
  - secure: ZlReqvu1UqUVR8rxzgM2DU8imXqkx5gfs0qTvcHuC279A/bE1mnBty1a5PQ6NFSvyPZgNAMlUiuRBgGl3lM3V0oViVEGfNfHd/fP1SykwXqFIYy0oPP7Q5oYLY1CQ2+L9QtXk0tj8X4qbSpfoUW463jCDrxg7m8hEngK94qisrWz6r2B9QBzndQQkUfaVyh3kPV6273ffiV+inwEMUw0pgopikbjkhaHopSdFj3H8PobVHKMIFUQIrUCV8BPwM5q5RPwNvanrLUnBMb9ZzYrYUa9GyLWxK5j+LR9cPTtj/4298i/Pl531YqAxqBbtJv+c8jP8l9pg+YnCY/e3NaaJr64vOyfA3kOPsZv1c7AWQXCzqiS8qqIrnD3rc3JB8TvhNjPbS6Btqui+R/WIIpO97xXs2k3WJl9AzDpdwTLKWBjzkm7q98i1ZikFgRLpM6aVQPsG8rcegC76QDZEXfm9Nz3zetTkSyTt9SxeaJSgBhgyjZtq7tLYiGcv8KPO5Nl5u7Yd1XF7cGLeH3mjf42gCKXB7fzhkm1WaPLEzwZH+xcHA23HYy/4U+0Rhmes8TMaOptQcR35m7wgLJ6Sncu0SWedtyUmwP++60Da499d0ejj8d22BtbnagxIB9X4n5JAmIJ/PM9Aj+vtvz/60Y+ItB0senvLVKTa8U9J0vwUnk=
